name: Commit CI

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - '**/**'
      - '!*.md'
      - '!.gitignore'
  pull_request:

jobs:
  build:
    runs-on: windows-2022
    steps:
    
      - name: Checkout last commit
        uses: actions/checkout@v3
        with:
          submodules: true
    
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

      # build Nvy
      - name: Build Nvy
        id: build_nvy
        shell: pwsh
        run: |
          set CC=cl
          set CXX=cl
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_CXX_FLAGS="/MT" -DCMAKE_C_FLAGS="/MT"
          cmake --build . --config Release
        if: ${{ success() }}

      # for branch master only
      - name: Create Nightly Release
        if: ${{ github.ref == 'refs/heads/master' && success() }}
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: "Nightly Build"
          files: |
            ./build/Release/Nvy.exe

      # for tags only
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') && success() }}
        with:
          files: |
            ./build/Release/Nvy.exe

      # for !tags
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: ${{ startsWith(github.ref, 'refs/heads/') && success() }}
        with:
          if-no-files-found: error
          path: |
            ./build/Release/Nvy.exe
